name: Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        ref: refs/pull/${{ github.event.pull_request.number }}/merge

    # Install node version 12
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Build
      run: docker run --rm -v $PWD:/src quay.io/gunnarmorling/hugo-builder bash -c "cd /src && /hugo/hugo -F"

    - name: Preview
      uses: afc163/surge-preview@v1
      id: preview_step
      with:
        surge_token: ${{ secrets.SURGE_TOKEN }}
        github_token: ${{ secrets.SURGE_GH_TOKEN }}
        dist: public

    - name: Get the preview_url
      run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
